### ISSUE TITLE
A error i can't solve ([Errno 5] EIO)

### ISSUE THREAD

**Issue by Maikelengelo** [balance19/micropython_DS3231#9]
I connected the DS3231 to my Pico: SDA to pin 16, SCL to pin 17, GND to GND and VCC to VSYS.
I copied the example code in main.py and put the RTC_DS3231.py in a my_lib folder. I didn't change any code.

When i tried to run the code I got the error: ([Errno 5] EIO) and when i tried Settime() in the example code I got: 
Traceback (most recent call last):
  File "<stdin>", line 13, in <module>
  File "my_lib/RTC_DS3231.py", line 26, in DS3231_SetTime
OSError: [Errno 5]  EIO

I tried to run a I2C address scan and got 0x57, but when a changed the address it still got the same error massages.

Does someone know how to solve this problem and make it work like intended?

**Comment by JoelGodin** [comment]
That address don't sound right.  Try 
def __init__(self, sda_pin=16, scl_pin=17, port=1, speed=100000, address=0x68, register=0x00):

**Comment by mrgcms01** [comment]
Pretty sure the pin numbers refer to GPIO pin numbers. I've got mine connected up to device pins 11 and 12, GPIO 8 and 9 and I use this to initialize the RTC  

rtc = RTC_DS3231.RTC(8,9,0,400000)

Try connecting to device pins 21 and 22 which are GPIO 16 and 17.
